- name: Install packages required for ODBC
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: installed
  with_items: "{{ apt_odbc_packages }}"

- name: Install packages required for ODBC
  yum:
    update_cache: yes
    name: "{{ item }}"
    state: installed
  with_items: "{{ apt_odbc_packages }}"

- name: Write custom ODBC driver configuration
  template:
    src: "{{ ODBCINST_TEMPLATE }}"
    dest: "{{ ODBCINSTPATH }}"
    mode: 0644

- name: Write custom ODBC DSN listing
  template:
    src: "{{ ODBC_TEMPLATE }}"
    dest: "{{ ODBCINI }}"
    mode: 0644
